# Generated by Django 4.2.6 on 2023-11-28 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=600)),
                ('tipo', models.CharField(choices=[('VACACIONES', 'Vacaciones'), ('FERIADO', 'Feriado'), ('SUSPENSION DE ACTIVIDADES', 'Suspensión de Actividades'), ('SUSPENSION DE ACTIVIDADES (PM)', 'Suspensión de Actividades (PM)'), ('CEREMONIA', 'Ceremonia'), ('EDDA', 'Edda'), ('EVALUACION', 'Evaluacion'), ('AYUDANTIAS', 'Ayudantias'), ('HITO ACADEMICO', 'Hito Academicas'), ('SECRETARIA ACADEMICA', 'Secretaria Academica'), ('OAI', 'Oai')], max_length=50)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.segmento')),
            ],
        ),
    ]
