# Generated by Django 4.2.6 on 2023-11-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_alter_segmento_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmento',
            name='tipo',
            field=models.CharField(choices=[('C', 'Comunidad USM'), ('E', 'Estudiante'), ('P', 'Profesor'), ('J', 'Jefe de Carrera')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='segmento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
