# Generated by Django 4.2.6 on 2023-11-28 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miapp', '0003_segmento_tipo_alter_segmento_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmento',
            name='nombre',
        ),
        migrations.AddField(
            model_name='segmento',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='segmento',
            name='tipo',
            field=models.CharField(choices=[('COMUNIDAD USM', 'Comunidad USM'), ('ESTUDIANTE', 'Estudiante'), ('PROFESOR', 'Profesor'), ('JEFE DE CARRERA', 'Jefe de Carrera')], max_length=50),
        ),
    ]
